/* Identifiers */

aB XXyy xyz ABC aa123 OP987 ab12xy ab78AB
12xyz 33ABC 01xYz12

/* keyword example */

if else while int string char return void

vooid iff

/* Integers */

1234 101 543 44
011 00
0

/* Characters */

'a' 'X' 'xyz' 'AbCd'
'1' '100'

/* Strings */

"abcd" "xyz123" "abc xyz 101" "a"

"Texas State University San Marcos \t Texas.\"78666 \\CSE dept"

"Texas State \\

"Texas State University \b San Marcos \a Texas"

"Texas State University
San Marcos
Texas - 78666"

"lekwfj\bopi3rp\b"

/* Operators */

+ - * / % < > <= >= == != = [ ] { } ( ) , ; @ ++ -- && || !

/* Comment */

/* This is a comment */

/* This is
not a 
valid comment */

/* ----- */
