int main(){
	/* ID & int & char */
	int a, b, abCD, x1, 1y;
	a = 10;
	b = 20;
	x1 = 1y;
	abCD = a + b * x1;

	char xyz = 'A';
	char abc = 'ABC';

	/* String */

	string str1, str2, str3, str4, str5;
	str1 = "Texas State University";
	str2 = "San Marcos - 78666\n";
	str3 = "Texas \tRodeo\n";
	str4 = "Computer
	Science
	Dept";
	str5 = "\nCompiler \x Construction.";

	printf("\n Computer \t Science \t Departemnt\" - COMAL\n");

	/* This is an
	multiline
	comment.
	It should be ignored.*/

	/*This is a comment not gonna terminate

}